spring:
  application:
    name: webscrape-goat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/raw_apparel
    username: postgres
    password: Zavala125#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

playwright:
  base-url: https://www.goatcom/en-ca/search?query=
  timeout: 30000